//Define all of the variables and set initial values
player1Choice=null
player2Choice=null
//computer chooses random number between 1 and 3
compChoice=Math.floor(Math.random()*(4-1)+1);
comfirm1Clicked=false
document.getElementById("Rock2").disabled=true
document.getElementById("Paper2").disabled=true
document.getElementById("Scissors2").disabled=true
document.getElementById("Confirm2").disabled=true


//Assigns values to each player's choice
function rock(){
    player1Choice="rock"
}

function paper(){
    player1Choice="paper"
}

function scissors(){
    player1Choice="scissors"
}

function rock2(){
    player2Choice="rock"
}

function paper2(){
    player2Choice="paper"
}

function scissors2(){
    player2Choice="scissors"
}

//Translates computer's random choice to an apporpriate value
//If the computer choice is 1, the value "Rock" will be assigned to the player 2 choice variable
//If the computer choice is 2, the value "Paper" wil be assigned to the player 2 choice variable
//If the computer choice is 3, the value "Scissors" will be assigned to the player 2 choice variable
function translateCompChoice(){
    if(compChoice==1){
        player2Choice="rock"
    }
    if(compChoice==2){
        player2Choice="paper"
    }
    if(compChoice==3){
        player2Choice="scissors"
    }
}

//This runs in the one player mode of our game when the player clicks on the confirm button. It takes the the choice of the player and compares it to the choice of the computer.
//If the choice of the player is the same as the choice of the computer, the page displays a "Tie" message.
//If the choice of the player is rock and the choice of the computer is paper, the computer has won and the page will display a message accordingly. If the opposite happens, the player has won and the page will display the message accordingly.
//If the choice of the player is rock and the choice of the computer is scissors, the player has won and the page will display a message accordingly. If the opposite happens, the computer has won and the page will display the message accordingly.
//If the choice of the player is paper and the choice of the computer is scissors, the computer has won and the page will display the message accordingly. If the opposite happens, the player has won and the page will display the message accordingly.
//All of this will happen only if the player has chosen an option. If they haven't the page will display a message prompting the player to choose an option.
//After this function runs, a new choice will be generated by the computer.
function confirmOnePlayer(){
    translateCompChoice()
    if(player1Choice==null){
        alert("Please choose an option")
    }
    if (player1Choice==player2Choice){
        concat=("You both chose " + player1Choice + "!")
        alert(concat)
    }
    else if(player1Choice=="rock"&&player2Choice=="scissors"){
        alert("Rock beats scissors! Player 1 has beat Player 2 :)")
    }
    else if(player1Choice=="scissors"&&player2Choice=="rock"){
        alert("Rock beats scissors! Player 2 has beat Player 1 :)")
    }
    else if(player1Choice=="rock"&&player2Choice=="paper"){
        alert("Paper beats rock! Player 2 has beat Player 1 :)")
    }
    else if(player1Choice=="paper"&&player2Choice=="rock"){
        alert("Paper beats rock! Player 1 has beat Player 2 :)")
    }
    else if(player1Choice=="paper"&&player2Choice=="scissors"){
        alert("Scissors beat paper! Player 2 has beat Player 1!")
    }
    else if(player1Choice=="scissors"&&player2Choice=="paper"){
        alert("Scissors beat paper! Player 1 has beat Player 2!")
    }

    player1Choice=null
    compChoice=Math.floor(Math.random()*(4-1)+1);
}


//This function runs when the first player clicks on their confirm button in the two player version of this game. The purpose of this function is to disable all of player 1's options.
//This also enables player 2's buttons so that they are able to select their choice.
function confirmTwoPlayer1P (){
    confirm1Clicked=true
    document.getElementById("Rock").disabled=true
    document.getElementById("Paper").disabled=true
    document.getElementById("Scissors").disabled=true
    document.getElementById("Confirm").disabled=true
    document.getElementById("Rock2").disabled=false
    document.getElementById("Paper2").disabled=false
    document.getElementById("Scissors2").disabled=false
    document.getElementById("Confirm2").disabled=false
}

//This function runs when the player clicks on the reset button on their screen in the two player mode.
//It enables all of player 1's options and disables player 2's options so that player can't cheat.
//Additionally, it sets both choices to empty so that previous choices are not used unintentionally.
function reset(){
    document.getElementById("Rock").disabled=false
    document.getElementById("Paper").disabled=false
    document.getElementById("Scissors").disabled=false
    document.getElementById("Confirm").disabled=false
    document.getElementById("Rock2").disabled=true
    document.getElementById("Paper2").disabled=true
    document.getElementById("Scissors2").disabled=true
    document.getElementById("Confirm2").disabled=true
    player1Choice=null
    player2Choice=null
}


//This function runs when the second player enters their choice in the two player mode of this game. It is used to compare player 1's choice with player 2's choice
//If the choice of the player is the same as the choice of the computer, the page displays a "Tie" message.
//If the choice of the player is rock and the choice of the computer is paper, the computer has won and the page will display a message accordingly. If the opposite happens, the player has won and the page will display the message accordingly.
//If the choice of the player is rock and the choice of the computer is scissors, the player has won and the page will display a message accordingly. If the opposite happens, the computer has won and the page will display the message accordingly.
//If the choice of the player is paper and the choice of the computer is scissors, the computer has won and the page will display the message accordingly. If the opposite happens, the player has won and the page will display the message accordingly.
//All of this will happen only if the player has chosen an option. If they haven't the page will display a message prompting the player to choose an option.

    function confirmTwoPlayer(){
        if(player1Choice==null){
            alert("Please choose an option")
        }
        if (player1Choice==player2Choice){
            concat=("You both chose " + player1Choice + "!")
            alert(concat)
        }
        else if(player1Choice=="rock"&&player2Choice=="scissors"){
            alert("Rock beats scissors! Player 1 has beat Player 2 :)")
        }
        else if(player1Choice=="scissors"&&player2Choice=="rock"){
            alert("Rock beats scissors! Player 2 has beat Player 1 :)")
        }
        else if(player1Choice=="rock"&&player2Choice=="paper"){
            alert("Paper beats rock! Player 2 has beat Player 1 :)")
        }
        else if(player1Choice=="paper"&&player2Choice=="rock"){
            alert("Paper beats rock! Player 1 has beat Player 2 :)")
        }
        else if(player1Choice=="paper"&&player2Choice=="scissors"){
            alert("Scissors beat paper! Player 2 has beat Player 1!")
        }
        else if(player1Choice=="scissors"&&player2Choice=="paper"){
            alert("Scissors beat paper! Player 1 has beat Player 2!")
        }
    }
